universe = vanilla
executable = /afs/cern.ch/user/l/lgiacome/sim_workspace_mpi_py3/WarPyECLOUD/simulations/cavity_round/cavity_round.job
arguments = ""
output = /afs/cern.ch/user/l/lgiacome/sim_workspace_mpi_py3/WarPyECLOUD/simulations/cavity_round/cavity_round.out
error = /afs/cern.ch/user/l/lgiacome/sim_workspace_mpi_py3/WarPyECLOUD/simulations/cavity_round/cavity_round.err
log = /afs/cern.ch/user/l/lgiacome/sim_workspace_mpi_py3/WarPyECLOUD/simulations/cavity_round/cavity_round.log
RequestCpus = 10
transfer_output_files = ""
+MaxRuntime = 172800
queue
